const prec = {};
prec["+"] = 2;
prec["-"] = 2;
prec["*"] = 3;
prec["÷"] = 3;
prec["%"] = 3;
prec["!"] = 4;
prec["√"] = 5;
prec["^"] = 5;
prec["sin"] = 10;
prec["cos"] = 10;
prec["tan"] = 10;
prec["csc"] = 10;
prec["sec"] = 10;
prec["cot"] = 10;
prec["ln"] = 10;
prec["log"] = 10;
prec["log10"] = 10;

export { prec };
